apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: 657093102493.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
    ports:
    - containerPort: 8080
  imagePullSecrets:
    - name: ecr-secret
