apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
     spec:  
      containers:
      - name: web
        image: 657093102493.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
        env:
          - name: DB_HOST
            value: "mysql"  
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            value: "your_mysql_password"
          - name: DB_NAME
            value: "employees"
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: ecr-secret
