name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: <region>  # e.g., us-west-2

    - name: Log in to Amazon ECR
      run: |
        echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.<region>.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t your-image-name .

    - name: Tag Docker image
      run: |
        docker tag your-image-name:latest <aws_account_id>.dkr.ecr.<region>.amazonaws.com/your-repo-name:latest

    - name: Push Docker image to Amazon ECR
      run: |
        docker push <aws_account_id>.dkr.ecr.<region>.amazonaws.com/your-repo-name:latest
