name: Build and Push Docker Image

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      run: |
       ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mysql

        # Build the webapp image
        docker build -t mysql .
        
        # Tag the image for ECR
        docker tag mysql:latest $ECR_URI:latest
        
        # Push the image to ECR
        docker push $ECR_URI:latest

    



