name: Build and Push to Amazon ECR

on:
  push:
    branches:
      - master  # This ensures the workflow runs only when merging to the master branch

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image for web application
        run: |
          docker build -t webapp .
          docker tag webapp:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/webapp:latest

      - name: Push Docker image to ECR (Web App)
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/webapp:latest

      - name: Build Docker image for MySQL
        run: |
          docker build -t mysql ./mysql
          docker tag mysql:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/mysql:latest

      - name: Push Docker image to ECR (MySQL)
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
