name: Build and Push Docker Image to ECR

# Trigger the workflow on push to the master branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and push the Docker image to ECR
      - name: Build and push image to ECR
        run: |
          # Define the image URI
          IMAGE_URI=${{ secrets.ECR_REPOSITORY_URL }}:latest

          # Build the Docker image
          docker build -t $IMAGE_URI .

          # Push the Docker image to Amazon ECR
          docker push $IMAGE_URI

      # Step 5: Log the pushed image URI
      - name: Output image URI
        run: echo "Pushed Docker image: ${{ secrets.ECR_REPOSITORY_URL }}:latest"
