name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (for advanced builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ${{ secrets.AWS_REGION }}

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        IMAGE_TAG=657093102493.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mysql:latest
        docker build -t $IMAGE_TAG .

    # Step 5: Push the Docker image to ECR
    - name: Push Docker image to Amazon ECR
      run: |
        IMAGE_TAG=657093102493.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/webapp:latest
        docker push $IMAGE_TAG
